### ISSUE TITLE
Add symlinks to hmz-sv.vcf and htz-sv.vcf

### ISSUE THREAD

**Issue by lsantuari** [GooglingTheCancerGenome/sv-gen#28]
Each data subfolder now contains the files `hmz.bam`, `hmz-sv.bam` and `htz-sv.bam`, with the relative `.bai` indices.
It would help to have also symlinks to the files `data/hmz-sv.vcf` and `data/htz-sv.vcf`, so that each subfolder contains all the necessary files for the downstream analysis.

**Comment by arnikz** [comment]
Do you mean that only the `*.vcf` files should be symlinked in all the `r{X}_i{Y}/cov{Z}` subdirs? And what about the other files `*.{bed,fasta,fa}` in this dir? Because these output files don't depend on the `XYZ` params, there are placed higher up or closer to `basedir`.
```
├── out
│   ├── indel
│   │   ├── hmz.bed
│   │   ├── hmz.fasta
│   │   ├── hmz-sv.bed
│   │   ├── hmz-sv.fasta
│   │   ├── hmz-sv.insertions.fa
│   │   ├── hmz-sv.vcf
│   │   ├── hmz.vcf
│   │   ├── htz-sv.bed
│   │   ├── htz-sv.fasta
│   │   ├── htz-sv.insertions.fa
│   │   ├── htz-sv.vcf
│   │   ├── r150_i500
│   │   │   ├── cov10
...
```
I'm a bit reluctant to update the rules because the [output](https://github.com/GooglingTheCancerGenome/sv-gen/blob/cf55bc4482b1ce81fbfedce385a9667acc312286/snakemake/rules/sim_genomes.smk#L66) must be propagated to this (unrelated) [rule](https://github.com/GooglingTheCancerGenome/sv-gen/blob/cf55bc4482b1ce81fbfedce385a9667acc312286/snakemake/rules/map_reads.smk#L53), which makes the code unnecessarily more involved. It should be much easier to make code adjustments downstream instead. Do you agree?

**Comment by lsantuari** [comment]
I agree. Let us keep the VCF files where they are now.
